channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - numpy==1.23.5
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.11.2
name: mlflow-env
